# general
random_seed: 11
neptune_project: cellarium/tissue-purifier
batch_size_per_gpu: 64
check_val_every_n_epoch: 20
checkpoint_interval_minutes: 25
model: vae
data_dir: ./slide_seq_testis
dataset: slide_seq_testis
num_workers: -1
max_time_minutes: 600
gradient_clip_algorithm: value
gradient_clip_val: 0.5
overfit_batches: 0
initialization_type: scratch
training: true
logging: true
precision: 32
predict: false
profiler: passthrough
detect_anomaly: false
deterministic: false

# validation
val_iomin_threshold: 0.0

# architecture
backbone_type: resnet18  # resnet18, resnet34, resnet50, vanilla
latent_dim: 1024
decoder_output_activation: identity
encoder_hidden_dims:  # used only if backbone type is vanilla
- 1
- 2
- 3

# loss
beta_vae_init: 0.1
momentum_beta_vae: 0.999

# optimizers
optimizer_type: adam
min_learning_rate: 1.0E-4
max_learning_rate: 5.0E-4
max_weight_decay: 1E-6
min_weight_decay: 1E-6
warm_up_epochs: 100
warm_down_epochs: 500
max_epochs: 1000

# dataset
n_crops_for_tissue_test: 600
n_crops_for_tissue_train: 600
load_count_matrix: false
n_neighbours_moran: 6
n_element_min_for_crop: 200
pixel_size: 4.0
image_in_ch: 9

# augmentations
n_global_crops: 1
n_local_crops: 0
global_size: 96
local_size: 64
dropouts:
- 0.1
- 0.2
- 0.3
global_scale:
- 0.8
- 1.0
local_scale:
- 0.6
- 0.8
occlusion_fraction:
- 0.1
- 0.3
rasterize_sigma:
- 0.5
- 1.0
