# general
random_seed: 11
neptune_project: cellarium/tissue-purifier
batch_size_per_gpu: 64
check_val_every_n_epoch: 10
checkpoint_interval_minutes: 5
model: dino
data_dir: ./slide_seq_testis
dataset: slide_seq_testis
num_workers: -1
max_time_minutes: 600
gradient_clip_algorithm: value
gradient_clip_val: 0.0
overfit_batches: 0
initialization_type: scratch
training: true
logging: true
precision: 32
predict: false
profiler: passthrough
detect_anomaly: false
deterministic: false

# validation
val_iomin_threshold: 0.0

# architecture
backbone_type: resnet50
backbone_pretrained: true
backbone_out_ch: 2048
head_bottleneck_ch: 256  # used only if head_type == dino
head_hidden_ch: 2048
head_out_ch: 60000
head_type: dino  # mlp or dino
head_use_bn: true

# optimizers
optimizer_type: 'lars'
min_learning_rate: 0.001 
max_learning_rate: 0.3
max_weight_decay: 1.0E-6
min_weight_decay: 1.0E-6
warm_up_epochs: 100
warm_down_epochs: 200
max_epochs: 400

# temperature
set_temperature_using_ipr_init: False  # if true temperature_init is disregarded, if false ipr_init is disregarded
temperature_student_init: 0.1
temperature_teacher_init: 0.04
ipr_student_init: 80
ipr_teacher_init: 40

# teacher update
center_momentum: 0.9
param_momentum_init: 0.996
param_momentum_final: 0.996
param_momentum_epochs_end: 1000000

# dataset
n_crops_for_tissue_test: 600
n_crops_for_tissue_train: 600
load_count_matrix: false
n_neighbours_moran: 6
n_element_min_for_crop: 200
pixel_size: 4.0
image_in_ch: 9

# augmentations
n_global_crops: 2
n_local_crops: 6
global_size: 96
local_size: 64
dropout_rates:
- 0.1
- 0.2
- 0.3
global_scale:
- 0.8
- 1.0
local_scale:
- 0.6
- 0.8
occlusion_fraction:
- 0.1
- 0.5
rasterize_sigma:
- 0.5
- 1.0
- 1.5
- 2.0
