# general
batch_size_per_gpu: 256
check_val_every_n_epoch: 100
checkpoint_interval_minutes: 25
model: vae
data_dir: ./slide_seq_testis
dataset: slide_seq_testis
num_workers: -1
max_time_minutes: 1440
gradient_clip_algorithm: value
gradient_clip_val: 0.5
overfit_batches: 0
initialization_type: scratch
training: true
logging: true
precision: 32
predict: false
profiler: passthrough
detect_anomaly: false
deterministic: false

# validation
val_iomin_threshold: 0.0

# architecture
vae_type: resnet34
decoder_output_activation: identity
encoder_hidden_dims:
- 32
- 64
- 128
- 256
- 512
latent_dim: 1024
image_size: 96

# loss
beta_vae_init: 0.1
momentum_beta_vae: 0.99

# optimizer
optimizer_type: adam
min_learning_rate: 1.0E-4
max_learning_rate: 5.0E-4
max_weight_decay: 0.0
min_weight_decay: 0.0

# protocoll
warm_up_epochs: 100
warm_down_epochs: 10000
max_epochs: 15000

# dataset
load_count_matrix: false
n_crops_for_tissue_test: 600
n_crops_for_tissue_train: 600
n_neighbours_moran: 6
n_element_min_for_crop: 200
pixel_size: 4.0
image_in_ch: 9

# augmentations
n_global_crops: 2
n_local_crops: 6
global_size: 96
local_size: 64
dropout_range:
- 0.1
- 0.3
global_scale:
- 0.8
- 1.0
local_scale:
- 0.6
- 0.8
occlusion_fraction:
- 0.1
- 0.3
rasterize_sigma:
- 0.5
- 2.0
